Compute the prefix of the breadcrumb from the URL
epfl-idevelop/container-wp-volumes pull request #26
Opened 2018-01-31 12:59 UTC by gilbrechbuhler

In order to respect site hierarchie. For example on https://www.epfl.ch/site1/site2/page1, we want the breadcrumb to be :

www.epfl.ch > site1 > site2 > page1

2018-02-01 08:59 UTC, LuluTchab requested changes
Juste quelques petites améliorations de code à faire 😄

2018-02-01 08:59 UTC, LuluTchab commented on wp-content/themes/epfl-master/functions.php
> +            $breadcrumb_parts[$temp_url] = $name;
Vu que `$name` n'est utilisé qu'ici, tu pourrais simplifier les 2 lignes en  :
`$breadcrumb_parts[$temp_url] = basename($temp_url);`

2018-02-01 08:59 UTC, LuluTchab commented on wp-content/themes/epfl-master/functions.php
> +        $temp_url = $site_url;
Cette ligne pourrait être supprimée si tu changes 2 lignes plus haut pour mettre :
`$temp_url = site_url();`

2018-02-01 08:59 UTC, LuluTchab commented on wp-content/themes/epfl-master/functions.php
> +            if ($i == 0) {
Tu peux te passer complètement de `$i` et mettre la condition suivante:
`if($base_breadcrumb=='') {`

2018-02-01 08:59 UTC, LuluTchab commented on wp-content/themes/epfl-master/functions.php
> +                $base_breadcrumb .= '<li class="item-home"><a class="bread-link bread-home" href="' . $url . '" title="' . $name . '">' . $name . '</a></li>';
Vu que du coup quand tu te retrouves ici la variable `$base_breadcrumb` est vide, la concaténation de chaîne est inutile et tu peux mettre direct `=` au lieu de `.=`

2018-02-02 07:33 UTC, gilbrechbuhler commented on wp-content/themes/epfl-master/functions.php
> +        $temp_url = $site_url;
Corrigé, merci

2018-02-02 07:33 UTC, gilbrechbuhler commented on wp-content/themes/epfl-master/functions.php
> +            $breadcrumb_parts[$temp_url] = $name;
Corrigé, merci

2018-02-02 07:34 UTC, gilbrechbuhler commented on wp-content/themes/epfl-master/functions.php
> +            if ($i == 0) {
Corrigé, merci

2018-02-02 07:34 UTC, gilbrechbuhler commented on wp-content/themes/epfl-master/functions.php
> +                $base_breadcrumb .= '<li class="item-home"><a class="bread-link bread-home" href="' . $url . '" title="' . $name . '">' . $name . '</a></li>';
Corrigé, merci

2018-02-02 07:44 UTC, LuluTchab requested changes
Encore juste un petit truc et ça sera bon ^^

2018-02-02 07:44 UTC, LuluTchab commented on wp-content/themes/epfl-master/functions.php
> +            $i++;
Tu peux aussi enlever celui-ci de `$i++` 😉

2018-02-02 07:47 UTC, gilbrechbuhler commented on wp-content/themes/epfl-master/functions.php
> +            $i++;
Houla, effectivement, je sais pas comment je l'ai raté, c'est corrigé.

2018-02-02 09:52 UTC, LuluTchab approved these changes

2018-02-12 15:34 UTC, gilbrechbuhler commented
Mise à jour :
- génération de labels plus propres lorsque le breadcrumb est construit à partir de l'URL
- gestion de l'option `epfl:custom_breadcrumb`

Dans un cas comme dans l'autre, seule le préfixe du breadcrumb est modifiée, par exemple sur l'URL `https://www.epfl.ch/site1/page1/page2`, le breadcrumb par défaut de wordpress est `Homepage > Page1 > Page2`, le code de cette PR ne modifie que la partie `Homepage`, ainsi, le breadcrumb généré depuis l'URL ressemblera à : `EPFL > Site1 > Page1 > Page2`

2018-02-13 13:47 UTC, gilbrechbuhler commented
- Ajout d'une vérification du format de l'option avec une expression régulière
- Ajout de 'https://' devant les URLs où il manque afin d'empêcher le navigateur de les traiters comme des liens relatifs
- Réduction du timeout du cache à 30 secondes.

A voir encore : est-il possible d'exécuter un hook lorsque les options d'EPFL-settings sont sauvegardées par l'utilisateur ( @lvenries ) ? Cela permettrait de mettre à jour le cache en direct lorsque l'option est modifiée, sinon on garde la solution du cache à court terme pour le moment.

2018-02-15 09:02 UTC, gilbrechbuhler commented
Je ferme celle-ci, après discussion on a décidé de centralisé ces modifications dans le repo jahia2wp.

2018-02-15 09:02 UTC, closed without merging